services:
    influxdb:
        image: influxdb:2.0.7
        volumes:
            - $HOME/docker/influxdb/data:/var/lib/influxdb
        environment:
            TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
            TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: iot
            DOCKER_INFLUXDB_INIT_BUCKET: airliner
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        ports:
            - "8086:8086"
